# Generated by Django 5.2.3 on 2025-06-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Укажите почту', max_length=254, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, help_text='Укажите телефон', max_length=35, null=True, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, help_text='Укажите город', max_length=50, null=True, verbose_name='Город')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars', verbose_name='Аватар')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
